### ISSUE TITLE
Fully automated Microsoft Store Releases

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#139]
There's this person, @LanceMcCarthy, who has [fully automated Microsoft Store Deployments of a msix packaged WPF App using a Github Actions Workflow](https://github.com/LanceMcCarthy/MediaFileManager/blob/main/.github/workflows/cd_release_msstore.yml). I don't know how the fuck he managed to do that exactly, but he seems to be a very skilled 10x awarded Microsoft MVP. I want to add this feature to our Pipeline too, as it would create a great CI/CD environment.

The Plan:
- [ ] The development branch will automatically release to Crackpipe (Developer Edition) on the Microsoft Store.
- [ ] The master branch will automatically release to Crackpipe on the Microsoft Store.

**Comment by LanceMcCarthy** [comment]
Hi Alper, I can help point you to some additional workflows that shows you how to accomplish this. Take a look at https://github.com/microsoft/github-actions-for-desktop-apps The RERADME has everything you need to build your pipeline.

One thing to be aware of is that WPF apps only support up to WinAppSDK 0,.8x, so if you're trying to use project reunion APIs, that might trip you up. This essentially means that _you cannot use the single-project MSIX approach_ that WinUI gets to use... you will have to add a new "PackageProject" to the Solution, this is what creates the MSIX package.

Please follow this tutorial for the rest of the instructions => https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/modernize-wpf-tutorial-5

Okay, once you've successfully built a store-ready package, the nest step in the workflow is to publish it tot he Microosft Store. the approach I use in MediafileManager is a bit outdated, that was the ling way around by using the older PowerShell stuff.

Today, you have a newer, better option, there's a dedicated Action that you can now use, and avoid the craziness I had to do.. Go here for more details => https://github.com/marketplace/actions/microsoft-store-publish 

Good luck!

**Comment by Alfagun74** [comment]
Hey Lance,  
  
Thanks for dropping by. We've got a Package Project locally, but it's not in the repo due to its massive size. Currently, we're manually building the bundle ourselves and deploying the .appxupload via Partner Center.
  
I've checked out the microsoft-store-publish action, but it doesn't seem to support .msix applications yet. So, it won't work for our packaged WPF Project, right? Here's the link to the issue: https://github.com/microsoft/store-submission/issues/12
  
By the way, while you're here, could you let me know how your pipeline handles the code certification via your self-signed certificate?
  
Cheers!

**Comment by LanceMcCarthy** [comment]
Happy to help, let me break down this reply:

## Commiting the PackageProject

The PackageProject itself is _very_ small, just make sure you're not committing the build result with the project. If necessary, just add the folder to the .gitignore

## MSIX

As to the appx/msix issue, you shouldn't be getting appx output anymore. They stopped the appx naming around SDK 18062 I think.  To get msix automatically, just add this line to your csproj => https://github.com/LanceMcCarthy/MediaFileManager/blob/6d77d1f055bf01bd08e0556c7b10585e82838a41/src/MediaFileManager/MediaFileManager.Desktop/MediaFileManager.Desktop.csproj#L5

That should automatically trigger MSBuild to give you an msix (or msixupload bundle).

> Don't worry, that version of Windows has long been out of support, so you won't be excluding users (unless you're still trying to get windows 8 and 7 folks). It's just the min that triggers the switch to msix.

## Code Signing

To your last question about code signing.

- If the app is being published to the Microsoft Store... you do **NOT** sign it. Microsoft will sign it with their cert before publishing (I thin it happens in the submission phase, before QA). If you accidentally signed it, the CN name will be incorrect and will not be able to get uploaded anyways

- However, if you plan on distribution side-loadable version, then yes you do need to code sign it. I have a separate workflow you can review => https://github.com/LanceMcCarthy/MediaFileManager/blob/main/.github/workflows/cd_release_sideload.yml 

Indeed, GitHub Actions doesn't let you upload/attach a secure file.... but there's a very easy fix for this. In summary, on your local PC you export the PFX as a base64... then _save that base64 as a Github Actions secret_!  In the wrokflow, you can use that secret's value to recreate the PFX file :) 

If you've never saved a GitHub Actions secret, you'll find it under the Settings tab:

![image](https://github.com/Phalcode/crackpipe-app/assets/3520532/7f7fbbbf-65ac-4c06-b4eb-7e023648fbe5)

At the top of my workflow, I'll set some env vars that help prevent annoying errors because I mistyped something. 

```yaml
    env:
      CertificateFileName: LancelotSoftwareLLC.pfx
      WappProjectPath: src\MediaFileManager\PackageProject\PackageProject.wapproj
      AppxPackageDirectory: D:\a\MediaFileManager\MediaFileManager\src\MediaFileManager\PackageProject\SideLoadPackages\
      ArtifactsFilePath: D:\a\MediaFileManager\MediaFileManager\src\MediaFileManager\PackageProject\SideLoadPackages\SideLoadPackages.zip
      AppInstUri: "https://dvlup.blob.core.windows.net/general-app-files/Installers/MediaFileManager/"
      TFM: net7.0-windows10.0.19041.0
      TargetPlatform: "x64"
      AppxBundlePlatforms: "x86|x64|arm64"
      AppxBundleMode: Always
      AppxBuildMode: SideloadOnly
      AppxPackageSigningEnabled: True
      GenerateAppInstallerFile: True
      HoursBetweenUpdateChecks: 12
```

Later on in the workflow, 

```yaml
# Decode the Base64 from the GitHub Secret and save as a PFX file, notice the following items
#   - ${{ secrets.LancelotSoftwareCert_Base64 }}
#   - ${{ env.CertificateFileName }}
    - name: Decode the Pfx
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.LancelotSoftwareCert_Base64 }}")
        $currentDirectory = Get-Location
        $certificatePath = Join-Path -Path $currentDirectory -ChildPath "src\MediaFileManager\PackageProject" -AdditionalChildPath "${{ env.CertificateFileName }}"
        [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)

# Now that was have a PFX file saved, we can use it to code sign the package, notice the following items:
#   - ${{ env.CertificatePassword }}    <-- this one is set by a secret
#   - ${{ env.CertificateFileName }}    <-- this one is set by a secret
- name: Build wapproj for Sideloading
      run: msbuild ${{ env.WappProjectPath }} /p:GenerateAppInstallerFile=${{ env.GenerateAppInstallerFile }} /p:AppInstallerUri=${{ env.AppInstUri }} /p:HoursBetweenUpdateChecks=${{ env.HoursBetweenUpdateChecks }} /p:AppxPackageDir=${{ env.AppxPackageDirectory }} /p:Configuration=${{ env.Configuration }} /p:UapAppxPackageBuildMode=${{ env.AppxBuildMode }} /p:AppxBundle=${{ env.AppxBundleMode }} /p:PackageCertificateKeyFile=${{ env.CertificateFileName }} /p:PackageCertificatePassword=${{ env.CertificatePassword }} /p:PackageCertificateThumbprint=${{ env.CertificateThumbprint }} /p:AppxPackageSigningEnabled=${{ env.AppxPackageSigningEnabled }} /p:Platform=${{ env.TargetPlatform }} /p:AppxBundlePlatforms="${{ env.AppxBundlePlatforms }}"
      env:
        CertificatePassword: ${{ secrets.LancelotSoftwareCert_Password }}
        CertificateThumbprint: ${{ secrets.LancelotSoftwareCert_Thumbprint }}

# not needed because the container gets deleted after it's run, but you can do it for peace of mind just in case you accidentally zip it up with the artifacts
    - name: Delete the PFX file
      run: |
        $currentDirectory = Get-Location
        $certificatePath = Join-Path -Path $currentDirectory -ChildPath "src\MediaFileManager\PackageProject" -AdditionalChildPath "${{ env.SigningCertificate }}"
        [IO.File]::Delete("$certificatePath")
```
