### ISSUE TITLE
Reading game library from NFS share

### ISSUE THREAD

**Issue by casudo** [Phalcode/gamevault-app#345]
**Your Question**

I am currently facing issues with the servers game library when I store them inside a NFS share.

**Additional Context**

Is this possible? I've set the permissions to read write, but the container cannot create files in the directory.

VM1 ../games -> NFS share to -> VM2 (mounted as ../games_nfs) -> Running Gamevault Backend Server as Container -> bind mount like this: /mnt/nfs_folders/games_nfs:/gamefiles

**Comment by Alfagun74** [comment]
Should not be an issue. Your permissions are set to read write but for whom? GameVault runs on userid 1000 and groupid 1000 by default. You can change it via env vars.

**Comment by casudo** [comment]
> Should not be an issue. Your permissions are set to read write but for whom? GameVault runs on userid 1000 and groupid 1000 by default. You can change it via env vars.

![image](https://github.com/Phalcode/gamevault-app/assets/55252063/3e53c39e-7afe-4d3b-a903-ecb7286848ea)
Inside of the container it looks like this. On the host in the VM the user and group is set to the default group of my normal user (not root).

**Comment by casudo** [comment]
I've changed PUID & PGID to 0 and now it shows me this:
![image](https://github.com/Phalcode/gamevault-app/assets/55252063/7c5c6ada-e4cc-40e1-bbfd-42aebbb01402)

**Comment by Alfagun74** [comment]
try chmodding to 777 to check if this is really the issue

**Comment by casudo** [comment]
> 1. try chmodding to 777 to check if this is really the issue
> 
>     2. whats the exact error you are facing, can you show me any logs?

chmodding to 777 helped me to create files in the directory, heres the output:
![image](https://github.com/Phalcode/gamevault-app/assets/55252063/859e86d4-eb31-4945-b76f-5dac1bfb7323)


Container logs:
![image](https://github.com/Phalcode/gamevault-app/assets/55252063/5d6bb879-85c2-4742-bf6c-34780224bb89)

**Comment by Alfagun74** [comment]
looks good to me, any further issues?

**Comment by casudo** [comment]
> looks good to me, any further issues?

Well, it still don't show the games in the client.

**Comment by Alfagun74** [comment]
Try restarting the server to reindex, or just press the reindex button in the admin panel on the client. And check your logs if the games got indexed

**Comment by casudo** [comment]
> Try restarting the server to reindex, or just press the reindex button in the admin panel on the client. And check your logs if the games got indexed

![image](https://github.com/Phalcode/gamevault-app/assets/55252063/6a7558f5-59f9-4e75-a437-7727d034dca2)

Those are the logs right after I restarted GameVault Server and started the GameVault Client (below the highlighted lines). There are still no games found.

**Comment by casudo** [comment]
![image](https://github.com/Phalcode/gamevault-app/assets/55252063/7939b6a8-ba33-4623-bcc6-6dae9ad355be)

and the log lines after manually clicking "Reindex games". The client respond that the reindex was successful.

**Comment by Alfagun74** [comment]
Try 777 on one of the Files aswell it definitely seems like a permissions issue

**Comment by casudo** [comment]
> Try 777 on one of the Files aswell it definitely seems like a permissions issue

Did that now. I've changed the permission to 777 for one of the .zip files in VM1 which shares the ../games folder. In the GameVault Server container running on VM2, I can see that the changes are correct (rwxrwxrwx). I restarted GameVault Server aswell as manually reindexed the games - no luck. The log lines were exactly the same.

**Comment by casudo** [comment]
I did an ls on VM2 which has the shared ../games folder from VM1 mounted, and the folder name ../games_nfs has a green background with blue text.
According [to this answer](https://unix.stackexchange.com/a/94505), this means the following:
> "Blue text with green background indicates that a directory is writable by others apart from the owning user and group, and does not have the sticky bit set (o+w, -t)."

**Comment by Alfagun74** [comment]
Show me your docker compose file please

**Comment by casudo** [comment]
> Show me your docker compose file please

```yaml
version: "3"

networks:
  database:
    external: true

services:
  gamevault:
    container_name: gamevault
    image: phalcode/gamevault-backend:latest
    restart: unless-stopped
    ports:
      - 8088:8080
    volumes:
      - /mnt/raid1/docker/gamevault/images:/images
      - /mnt/raid1/nfs_shares/games_nfs:/gamefiles
    environment:
      - TZ=Europe/Berlin
      - DB_HOST=postgresql # PostgreSQL Container Name
      - DB_USERNAME=myuser # PostgreSQL Username
      - DB_PASSWORD=mypassword # PostgreSQL Password
      - DB_NAME=gamevault # Gamevault's PostgreSQL Database Name
      - SERVER_ADMIN_USERNAME=gavakea # Gamevault Admin Username
    hostname: gamevault
    networks:
      - database
```
