### ISSUE TITLE
Game boxes not showing

### ISSUE THREAD

**Issue by casudo** [Phalcode/gamevault-app#346]
**Your Question**
I've recently added my GameVault library as NFS share and now I cannot see any game boxes in the server game preview.

**Additional Context**
Before I've used NFS share, I could see the boxes.

Docker Compose:
```yaml
version: "3"

networks:
  database:
    external: true

services:
  gamevault:
    container_name: gamevault
    image: phalcode/gamevault-backend:latest
    restart: unless-stopped
    ports:
      - 8088:8080
    volumes:
      - /mnt/arrmedia/games_nfs:/files
      - /mnt/docker/gamevault/images:/images
    environment:
      - TZ=Europe/Berlin
      - DB_HOST=postgresql # PostgreSQL Container Name
      - DB_USERNAME=myuser # PostgreSQL Username
      - DB_PASSWORD=mypass # PostgreSQL Password
      - DB_NAME=gamevault # Gamevault's PostgreSQL Database Name
      - SERVER_ADMIN_USERNAME=myuser # Gamevault Admin Username
    hostname: gamevault
    networks:
      - database
```

![image](https://github.com/Phalcode/gamevault-app/assets/55252063/6f298822-d9a8-4109-aeaa-2aaf5cbab38f)
