### ISSUE TITLE
Enhance Cloud Saves Configuration to Support Custom Manifests

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/gamevault-app#479]
##Background
Currently, we dynamically generate an isolated Ludusavi configuration, as outlined in [issue #477](https://github.com/Phalcode/gamevault-app/issues/477). However, this approach disregards secondary manifests, which some users rely on to define their own backup entries.

## Objective
We need to provide users with the ability to include their own custom manifest files, ensuring that their configurations are respected.

## Requirements
- [ ] Add a **settings option** allowing users to specify custom `manifest.yaml` files through either:
  - A **file path** (local manifest)
  - A **URL** (remote manifest)
- [ ] Ensure that the specified custom manifests are referenced in the generated `config.yaml`.

## Expected Configuration Format
Once implemented, the autogenerated `config.yaml` should properly reference user-defined manifests:

```yaml
manifest:
  enable: true
  secondary:
    - url: "https://mymanifest.com"  # URL-based method
      enable: true
    - path: "C:\\MyManifest\\manifest.yaml"  # File-based method
      enable: true
```

## Notes
- The option should be flexible enough to allow users to manage multiple manifests. An idea would be to offer a menu like ludusavi does: 
  ![Image](https://github.com/user-attachments/assets/ff1fd0d0-eef0-4c6c-bb13-cb0f6782aca0)
